** About

I use [[http://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard][Dvorak]] as my global system layout, but as Emacs input methods are
intended to be used with the QWERTY layout, I made this package with
some additional input methods that may be used with the Dvorak layout.
See [[http://www.emacswiki.org/emacs/WritingRussianWithDvorak][EmacsWiki: Writing Russian With Dvorak]] for a more detailed
description of this problem.

Files from this package are based on
[[http://www.emacswiki.org/emacs/download/cyrillic-dvorak.el]].  Many thanks
to its author kirill.

** Installation and Usage

*** Automatic

You may install this package using [[https://github.com/quelpa/quelpa][Quelpa]]:

#+BEGIN_SRC emacs-lisp
(quelpa '(dvorak-layouts :fetcher github :repo "alezost/dvorak-layouts.el"))
#+END_SRC

After installation, =dvorak-…= input methods will become available for
=set-input-method= and =toggle-input-method= (bound to =C-\= by default)
commands.

Alternatively, you can use =M-x dvorak-…= commands to switch an input
method.

*** Manual

Clone the repo and add the directory to =load-path=:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/path/to/dvorak-layouts")
#+END_SRC

Now you can either add autoloads for the commands:

#+BEGIN_SRC emacs-lisp
(autoload 'dvorak-qwerty "dvorak-qwerty" nil t)
(autoload 'dvorak-russian-computer "dvorak-russian-computer" nil t)
#+END_SRC

or require a package you need:

#+BEGIN_SRC emacs-lisp
(require 'dvorak-russian-computer nil t)
#+END_SRC
